# Generated by Django 4.2.30 on 2026-05-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_type", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=20)),
                (
                    "factor_kg_co2e",
                    models.DecimalField(decimal_places=6, max_digits=12),
                ),
                ("source", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=50)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
