# Generated by Django 4.2.30 on 2026-05-27 06:42

from django.db import migrations, models

def seed_airports(apps, schema_editor):
    Airport = apps.get_model('emissions', 'Airport')
    airports = [
        {'iata_code': 'STR', 'name': 'Stuttgart Airport', 'latitude': 48.6899, 'longitude': 9.2220},
        {'iata_code': 'FRA', 'name': 'Frankfurt Airport', 'latitude': 50.0379, 'longitude': 8.5622},
        {'iata_code': 'MUC', 'name': 'Munich Airport', 'latitude': 48.3538, 'longitude': 11.7861},
        {'iata_code': 'TXL', 'name': 'Berlin Tegel Airport', 'latitude': 52.5597, 'longitude': 13.2877},
        {'iata_code': 'BER', 'name': 'Berlin Brandenburg Airport', 'latitude': 52.3667, 'longitude': 13.5033},
        {'iata_code': 'LHR', 'name': 'London Heathrow Airport', 'latitude': 51.4700, 'longitude': -0.4543},
        {'iata_code': 'JFK', 'name': 'New York JFK Airport', 'latitude': 40.6413, 'longitude': -73.7781},
        {'iata_code': 'BOS', 'name': 'Boston Logan Airport', 'latitude': 42.3656, 'longitude': -71.0096},
        {'iata_code': 'PVG', 'name': 'Shanghai Pudong Airport', 'latitude': 31.1443, 'longitude': 121.8083},
        {'iata_code': 'SIN', 'name': 'Singapore Changi Airport', 'latitude': 1.3644, 'longitude': 103.9915},
    ]
    for ap in airports:
        Airport.objects.create(**ap)

def rollback_airports(apps, schema_editor):
    Airport = apps.get_model('emissions', 'Airport')
    Airport.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0002_seed_emission_factors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iata_code",
                    models.CharField(db_index=True, max_length=3, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.RunPython(seed_airports, rollback_airports),
    ]

