# Generated by Django 4.2.30 on 2026-05-26 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sap_fuel", "SAP Fuel & Procurement"),
                            ("utility", "Utility Electricity"),
                            ("travel", "Corporate Travel"),
                        ],
                        max_length=50,
                    ),
                ),
                ("uploaded_file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=50,
                    ),
                ),
                ("row_count", models.IntegerField(blank=True, null=True)),
                ("error_count", models.IntegerField(blank=True, null=True)),
                ("processing_log", models.TextField(blank=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_row_number", models.IntegerField()),
                ("activity_type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("activity_date", models.DateField()),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("facility_code", models.CharField(blank=True, max_length=50)),
                ("facility_name", models.CharField(blank=True, max_length=255)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("unit", models.CharField(max_length=20)),
                (
                    "original_quantity",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                ("original_unit", models.CharField(max_length=20)),
                (
                    "scope",
                    models.IntegerField(
                        choices=[
                            (1, "Scope 1 — Direct"),
                            (2, "Scope 2 — Indirect"),
                            (3, "Scope 3 — Other Indirect"),
                        ]
                    ),
                ),
                (
                    "emission_factor",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                (
                    "co2e_kg",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("raw_data", models.JSONField(default=dict)),
                ("source_metadata", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("flagged", "Flagged — Suspicious"),
                            ("locked", "Locked for Audit"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("flag_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="ingestion.datasource",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
